### PR TITLE
Rename the default branch from 'master' to 'main'

### LINKED ISSUE #175: Create a tweet button links to master branch instead of main by default
**What happened?**

The default `tweets/README.md` file throws a 404 page not found error when the Create New Tweet button in it is pressed.

Repro:
* Make a new GitHub org. Do not change any settings for default branch in the org.
* Make a brand new GitHub repo in that org
* Attempt to set up Twitter Together by cloning, setting up and pushing the repo from your development env (without deviating from this repo's instructions)
* Merge the setup PR
* Try to click on the Create New Tweet button in `tweets/README.md` in your repo

**What did you expect to happen?**

I would expect the page to show the GitHub file composer ready for me to write a new tweet.

**What the problem might be**

The problem lies in fetching the file for the setup PR from this repo:
https://github.com/gr2m/twitter-together/blob/4fabe65750bfc7eda4b15b5fe9d9e5f52652b572/lib/push/setup.js#L35-L47

This repo's `tweets/README.md` file defaults to referring to the master branch instead of the main branch.

**Resolution**

This issue could be resolved by developers manually changing the files as is necessary during setup to refer to the correct branch.

In the long term, renaming this repo's default branch from `master` to `main` alongside documentation/readme changes would help resolve this issue. 

If someone wants me to file a PR to make those documentation/readme changes, I would be more than happy to make them, although it would probably break the workflow on this repo if this repo's default branch is not renamed (because this repo's copy of `tweets/README.md` would have to be modified).

### PR DESCRIPTION
**Pull request by sau226**
Currently, GitHub defaults to creating all repositories with 'main' as the default branch name unless manually overridden. 

Because the setup tool pulls the README file from this repository, the link provided to create a new Tweet by default is broken. This rectifies that issue and makes administrative adjustments to documentation and CI to ensure that this is consistent across the repo.

No existing users are impacted, except this repo will need its default branch renamed to "main" (ideally via GitHub's web tools, so that redirects and other mitigations are implemented on the GitHub end), or the tweet file will need to be somehow made non branch specific/able to be pulled from an alternate location. 

This change is made to ensure that new users have an initial setup experience that works by default the vast majority of the time, instead of presenting an option that is less likely to work for new users "out of the box".

Issue link: Resolves #175

### CODE REVIEW

**Review by gr2m — CHANGES_REQUESTED** [review]
We will need to update the release configuration so that releases happen from the `main` branch in 

https://github.com/gr2m/twitter-together/blob/c1d95fd4bc6f3543a894116c69b8931bb7e16abe/package.json#L33-L54

We can set it to the same as 

https://github.com/octokit/octokit.js/blob/58dfd8a1dff4a4669b4aeea14c2fa2b8580093ad/package.json#L79-L91

Otherwise this should be good to go, thank you 👍🏼

**Comment by sau226** [comment]
I've copied the release configuration over from octokit/octokit.js as requested

**Review by gr2m — CHANGES_REQUESTED** [review]
The tests will need to be updated. Some of the test files contain `master` in their name, and `master` is still used in the tests and fixtures. Could you update the test names and do a global search for `master` with Match Case and Match Whole Word option? That way you should find the remaining places where `master` is still used

**Comment by sau226** [comment]
I ran the global search as you requested and made changes. 

There is a tweet file (in root folder that says "self referential") that still refers to the master branch, but I didn't make any changes there owing to the nature of that file.

**Review by gr2m — APPROVED** [review]
Thank you 👍🏼

**Pull request merged**
